### ISSUE TITLE
Add option to remove text from infoboxes.

### ISSUE THREAD

**Issue by larsRikard** [queicherius/runelite-time-tracking-reminder#41] opened 2023-04-28 20:34 UTC
let us hide the "ready" text from the infoboxes to make them more muted. Would be nice when making them small in the runelite settings.

**Comment by queicherius** [comment] 2023-04-29 16:40
Duplicate of https://github.com/queicherius/runelite-time-tracking-reminder/issues/32

**Closed by queicherius** 2023-04-29 16:40 UTC
