### ISSUE TITLE
Request to add Special patches (Mushrooms, Belladonna)

### ISSUE THREAD

**Issue by ShinsoTheOnion** [queicherius/runelite-time-tracking-reminder#29] opened 2023-02-05 19:21 UTC
As the title says,

would it be possible to add trackers for the Mushroom patch and Belladonna patches?

**Comment by queicherius** [comment] 2023-02-05 20:10
Duplicate of https://github.com/queicherius/runelite-time-tracking-reminder/issues/25

**Closed by queicherius** 2023-02-05 20:10 UTC
