### ISSUE TITLE
Farming contract infobox appears when it shouldn't.

### ISSUE THREAD

**Issue by Noctirvia** [queicherius/runelite-time-tracking-reminder#21] opened 2022-07-14 20:30 UTC
If a plot is occupied by the wrong plant the farming contract infobox appears.
Example: Farming contract is Maple Tree. The plot is occupied by Yew Tree. Plugin displays infobox.

**Comment by queicherius** [comment] 2022-07-14 20:32
Yes, this is the intended behaviour.

The plugin is telling you that your farming contract is "ready" because you need to take an action (planting a different tree) before your contract is in the "waiting for growing" stage (where it will hide the infobox).

**Comment by Noctirvia** [comment] 2022-07-14 20:36
Thanks for the **IMMEDIATE** response. Unfortunately in the example

**Comment by queicherius** [comment] 2022-07-14 21:01
> Unfortunately in the example the infobox will be displayed for the entire 400 minutes it takes the yew tree to grow. Plots cannot be changed until the currently growing plant is finished.

Yeah this is a bit of an annoying side-effect, but it would take quite a bit of extra implementation effort to handle this case so I am not sure that's worth it. 🤔

**Comment by queicherius** [comment] 2022-11-14 21:14
Closed by #24 thank you to @pelletier2017 -- the implementation there was a lot better than what I had in mind.

**Closed by queicherius** 2022-11-14 21:14 UTC
