### ISSUE TITLE
Separate infobox for crystal tree

### ISSUE THREAD

**Issue by itssapir** [queicherius/runelite-time-tracking-reminder#37] opened 2023-03-30 21:19 UTC
At the moment I think crystal tree gets bundled up with normal trees or something (hardwood maybe?).
Since these have vastly differing growth times it would be amazing if the crystal tree had its own info box similar to the Calquat patch.

**Comment by queicherius** [comment] 2023-03-30 21:43
Duplicate of #23

**Closed by queicherius** 2023-03-30 21:43 UTC
